spring:
  application:
    name: jeecg-system
  profiles:
    active: '@profile.name@'
    #在application.properties/或者application.yml文件中没有添加数据库配置信息.
    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver


